etools-profile-dropdown.html

Loading msg from element must not be fired every time, otherwise will break app loading msgs display

Loading msg fix

---

etools-profile-dropdown.html
user-profile-dialog.html

Clear changes on dialog dismiss 

---

bower.json
user-profile-dialog.html

update deprecated dropdowns

---

bower.json
etools-profile-dropdown.html

Fxed a console error in IE 11

---

bower.json
etools-profile-dropdown.html
user-profile-dialog.html

Comments out most fields from profile dropdown

---

etools-profile-dropdown.js
package.json
scripts/lodash.js
user-profile-dialog.js

Updated lodash dependency

---

user-profile-dialog.html

Adds name field to profile dialog

---

user-profile-dialog.js

Adds name field to etools-profile-dropdown

---

README.md
package.json
user-profile-dialog.js

Prepare for npm

---

.gitignore
package.json
user-profile-dialog.js

adjusted readonly styles and removed save button if the fields are not editable

adjusted readonly styles

---

package.json
user-profile-dialog.js

[ch19003] Profile dialog- style issue on mobile

[ch19003] Profile dialog- field cut off on mobile view

---

README.md
etools-profile-dropdown.js
package-lock.json
package.json
user-profile-dialog.js

[ch24824]Use etools-dialog shadow parts and remove the use of @apply

---

package-lock.json
package.json

Updated etools-dialog version

---

package-lock.json
package.json

[ch26414]Update dropdown

---

.npmignore
package-lock.json
package.json
user-profile-dialog.js

[ch27217]Remove dependency on etools-dropdown, add .npmignore

---

package-lock.json
package.json
user-profile-dialog.js

[ch27592]Handle empty coutries, groups

---

package-lock.json
package.json

Use migrated components (latest)

Use migrated components (latest)

---

etools-profile-dropdown.d.ts
etools-profile-dropdown.js
package-lock.json
package.json
user-profile-dialog.d.ts
user-profile-dialog.js

[ch28079] Migrate to LitElement  `etools-profile-dropdown` component

[ch28079] Migrate to LitElement  `etools-profile-dropdown` component

---

assets/translations/all.js
etools-profile-dropdown.js
package-lock.json
package.json
user-profile-dialog.js
utils/translate.js

[ch30675]Localize component

---

etools-profile-dropdown.js
package-lock.json
package.json
user-profile-dialog.js

[ch33272] Adapt padding, margin, left/right for rtl direction

[ch33272] Adapt padding, margin, left/right for rtl direction 8.2.0
